### ISSUE TITLE
color.el

### ISSUE THREAD

**Issue by casouri** [hlissner/emacs-doom-themer#2]
I just found this built-in library color.el that provides some color manipulation functions. And I remembered that you are writing a themer library. Maybe you'll find it useful, just FYI.

**Comment by alphapapa** [comment]
Yeah, it's in Emacs but easily missed.  Actually there are a few functions that ought to be contributed upstream to it, like blending...

**Comment by casouri** [comment]
Plus its use of Unicode in the source is brilliant. Very cool.

**Comment by alphapapa** [comment]
Huh, I hadn't noticed that before.  Cool.
